#pragma once

#define VICONDATASTREAMSDK_DOTNET_VERSION_REVISION_CONTROL_SYSTEM "unknown"
#define VICONDATASTREAMSDK_DOTNET_VERSION_REVISION 0
#define VICONDATASTREAMSDK_DOTNET_VERSION_MONOTONIC_REVISION 0
#define VICONDATASTREAMSDK_DOTNET_VERSION_PUBLIC_REVISION_STRING "0"
#define VICONDATASTREAMSDK_DOTNET_VERSION_BRANCH "unknown"
#define VICONDATASTREAMSDK_DOTNET_VERSION_REPOSITORY "unknown"
#define VICONDATASTREAMSDK_DOTNET_VERSION_CHANGESET "0"
#define VICONDATASTREAMSDK_DOTNET_VERSION_LOCAL_CHANGESET "0"
#define VICONDATASTREAMSDK_DOTNET_VERSION_LOCAL_BRANCH "unknown"

#define VICONDATASTREAMSDK_DOTNET_VERSION_MAJOR 1
#define VICONDATASTREAMSDK_DOTNET_VERSION_MINOR 11
#define VICONDATASTREAMSDK_DOTNET_VERSION_POINT 0
#define VICONDATASTREAMSDK_DOTNET_VERSION_RELEASE ""
#define VICONDATASTREAMSDK_DOTNET_VERSION_SUPPLEMENTAL ""

#define VICONDATASTREAMSDK_DOTNET_FULL_VERSION_STRING "1.11.0.0"
#define VICONDATASTREAMSDK_DOTNET_VERSION_STRING "1.11"
#define VICONDATASTREAMSDK_DOTNET_COMPANY "Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_DOTNET_COPYRIGHT "Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_DOTNET_TRADEMARK "Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_DOTNET_PROJECT_NAME "ViconDataStreamSDK_DotNET"

#define VICONDATASTREAMSDK_DOTNET_FULL_VERSION_STRING_L L"1.11.0.0"
#define VICONDATASTREAMSDK_DOTNET_VERSION_STRING_L L"1.11"
#define VICONDATASTREAMSDK_DOTNET_COMPANY_L L"Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_DOTNET_COPYRIGHT_L L"Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_DOTNET_TRADEMARK_L L"Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_DOTNET_PROJECT_NAME_L L"ViconDataStreamSDK_DotNET"
