#pragma once

#define VICONDATASTREAMSDK_MATLAB_VERSION_REVISION_CONTROL_SYSTEM "unknown"
#define VICONDATASTREAMSDK_MATLAB_VERSION_REVISION 0
#define VICONDATASTREAMSDK_MATLAB_VERSION_MONOTONIC_REVISION 0
#define VICONDATASTREAMSDK_MATLAB_VERSION_PUBLIC_REVISION_STRING "0"
#define VICONDATASTREAMSDK_MATLAB_VERSION_BRANCH "unknown"
#define VICONDATASTREAMSDK_MATLAB_VERSION_REPOSITORY "unknown"
#define VICONDATASTREAMSDK_MATLAB_VERSION_CHANGESET "0"
#define VICONDATASTREAMSDK_MATLAB_VERSION_LOCAL_CHANGESET "0"
#define VICONDATASTREAMSDK_MATLAB_VERSION_LOCAL_BRANCH "unknown"

#define VICONDATASTREAMSDK_MATLAB_VERSION_MAJOR 1
#define VICONDATASTREAMSDK_MATLAB_VERSION_MINOR 11
#define VICONDATASTREAMSDK_MATLAB_VERSION_POINT 0
#define VICONDATASTREAMSDK_MATLAB_VERSION_RELEASE ""
#define VICONDATASTREAMSDK_MATLAB_VERSION_SUPPLEMENTAL ""

#define VICONDATASTREAMSDK_MATLAB_FULL_VERSION_STRING "1.11.0.0"
#define VICONDATASTREAMSDK_MATLAB_VERSION_STRING "1.11"
#define VICONDATASTREAMSDK_MATLAB_COMPANY "Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_MATLAB_COPYRIGHT "Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_MATLAB_TRADEMARK "Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_MATLAB_PROJECT_NAME "ViconDataStreamSDK_MATLAB"

#define VICONDATASTREAMSDK_MATLAB_FULL_VERSION_STRING_L L"1.11.0.0"
#define VICONDATASTREAMSDK_MATLAB_VERSION_STRING_L L"1.11"
#define VICONDATASTREAMSDK_MATLAB_COMPANY_L L"Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_MATLAB_COPYRIGHT_L L"Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_MATLAB_TRADEMARK_L L"Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_MATLAB_PROJECT_NAME_L L"ViconDataStreamSDK_MATLAB"
